#!/bin/sh
query=$(echo "" | dmenu -p "Search:" | tr ' ' '+')
if [ "$query" ]; then
	query=$(curl -s "https://www.youtube.com/results?search_query=""$query""&sp=EgIQAQ%253D%253D")
	vid=$( echo "$query" | grep -Po '(/watch\?v=.{11})|(?<=title":{"runs":\[{"text":").+?(?="}\])' \
	| paste - - | dmenu -l 10 | cut -f2 || notify-send "Something went wrong...")
	[ "$vid" ] && mpv "https://youtube.com""$vid"
else
	notify-send "No query, closing."
fi
